# Generated by Django 5.0.4 on 2024-05-06 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_tutorial_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 6, 20, 53, 48, 411752, tzinfo=datetime.timezone.utc), verbose_name='date published'),
        ),
    ]
